services:
  simulator:
    container_name: "simulator"
    image: registry.sipgate.net/docker/sipgate/service/li-simulator-x1x2x3:development
    env_file: ./docker/simulator/.env
    volumes:
      - "mutual-tls-stores:/mutual-tls-stores"
    build:
      context: .
      args:
        MVN_ADDITIONAL_ARGS: "-DskipTests"
    ports:
      - "127.0.0.1:8080:8080" # REST API
      - "127.0.0.1:42069:42069" # X2X3
      - "127.0.0.1:5005:5005" # JVM remote debug
    networks:
      - li-network
    depends_on:
      init-admf-x1-stores:
        condition: service_completed_successfully
      init-ne-x1-stores:
        condition: service_completed_successfully
