services:
  simulator:
    container_name: "simulator"
    image: registry.sipgate.net/docker/sipgate/service/li-simulator-x1x2x3:development
    env_file: ./docker/simulator/.env
    build:
      context: .
      args:
        MVN_ADDITIONAL_ARGS: "-DskipTests"
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - li-network
    command: java -jar /app/simulator.jar
