spring:
  application:
    name: simulator
sipgate:
  li:
    simulator:
      targetUri: https://localhost/X1/NE
      admfIdentifier: admf-id
      clientCertKeyStore:
        path: "/tmp/keystore.p12"
        password: changeit
      serverCertTrustStore:
        path: "/tmp/truststore.jks"
        password: changeit

management:
  endpoints:
    web:
      base-path: /
