spring:
  application:
    name: simulator
sipgate:
  li:
    simulator:
      targetUri: https://localhost/X1/NE
      admfIdentifier: admf-id
      clientCertKeyStore:
        path: "/tmp/keystore.p12"
        password: changeit
      serverCertTrustStore:
        path: "/tmp/truststore.jks"
        password: changeit
      x2x3Server:
        maxHeaderLength: 320 # currently quite arbitrary
        maxPayloadLength: 8192 # currently quite arbitrary
        port: 42069
        sslEnabled: true
    networkElement:
      clientCertKeyStore:
        path: "/mutual-tls-stores/network-element-keystore.p12"
        password: changeit
      serverCertTrustStore:
        path: "/mutual-tls-stores/network-element-truststore.jks"
        password: changeit

management:
  endpoints:
    web:
      base-path: /

logging:
  level:
    com.sipgate: DEBUG
