spring:
  application:
    name: simulator
sipgate:
  li:
    simulator:
      targetUri: https://localhost/X1/NE
      admfIdentifier: admf-id
      clientCertKeyStore:
        path: "docker/network-element/client1.pfx"
        password: password
      serverCertTrustStore:
        path: "docker/network-element/server.pfx"
        password: password

management:
  endpoints:
    web:
      base-path: /
