---
name: Build and push docker image
concurrency: build-and-push
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build]
  push:
    branches:
      - main

jobs:
  pipeline:
    uses: sipgate/workflows/.github/workflows/pipeline-docker-image.yaml@main
    with:
      docker_image: ${{ github.event.repository.name }}
      skip_analysis: true
      test_image: sipgate/buildjava_21:bullseye
    secrets: inherit
