---
name: Build, docker push, mvn deploy
concurrency: build-and-push
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build]
  push:
    branches:
      - main

jobs:
  docker:
    uses: sipgate/workflows/.github/workflows/pipeline-docker-image.yaml@main
    with:
      docker_image: ${{ github.event.repository.name }}
      test_command: ./scripts/run-e2e-tests.sh
      skip_analysis: true
      test_image: sipgate/buildjava_21:bullseye
    secrets: inherit

  maven:
    uses: sipgate/workflows/.github/workflows/maven-package.yaml@main
    with:
      maven_docker_tag: 3.9
    secrets: inherit
