---
name: Build and deploy
concurrency: build-and-push
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build]
  push:
    branches:
      - main

jobs:
  # service
  docker:
    uses: sipgate/workflows/.github/workflows/pipeline-docker-classic.yaml@main
    with:
      service_name: ${{ github.event.repository.name }}
      test_command: true
      skip_analysis: true
    secrets: inherit

  # library for other projects (mostly used for tests)
  maven:
    needs: docker
    uses: sipgate/workflows/.github/workflows/maven-package.yaml@main
    with:
      maven_docker_tag: 3.9
    secrets: inherit
